{% set name = "typeguard" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33243c1cbfcb9736a06c6db22dd08876b5f297e6344aa272a2862c0f8e669f64

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools_scm
  run:
    - python >=3.4

test:
  imports:
    - typeguard

about:
  home: https://github.com/agronholm/typeguard
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Runtime type checker for Python
  description: |
    This library provides runtime type checking for functions defined with argument type annotations.
  doc_url: https://github.com/agronholm/typeguard
  dev_url: https://github.com/agronholm/typeguard

extra:
  recipe-maintainers:
    - itamarst
    - agronholm
