travis:
  secure:
    BINSTAR_TOKEN: sfnSe/gVC23/EJzqdpto4yVz8JLSHbMy9My3+S/MV4NUVgpwwSHlKrtfc5eqRSZBnli3UA3O2McQnX5WSpnvG0gfjnDb+fxSa1nGxebVy+wCAzTSIQYEAQ5i4Q0tl5eJldBFSxoG93pQ7Py4LCHiqjUQMLsdUzleOdf0DL9WVqea9rcVYHjcu2LQuEdmJ/mNnz8Am+xx5o8hsC28AuGOpqtFekeGCIWETgbRlryWi87wyrlvx/KUKt3qdaKnomM35M8iTWThnKQkLFsEicntrte0wczatN26M6Qz/zQ7ot12e4tiX5qP5RUHMqD8hTj/AYiMTmEirSMRzyqkW/CnpIXaBNc6uOaggV9vS2Pgjkb3cc4SNwT4ha2qW174u5tTplkiuCewrIcbjEPjV0rc0Mij0eAiFZGLDgpmeJz3LLL7u2Vun4uSX9YvHfhEnbmrDVJgzLuf3GbqqQ0zLfhleRH6erhnlRctuTmZO9AuxQoTeKmPzRPBs/WAVNaLFwz4UvuMPhsD8BdyFX11SX2GAidxgJl77wCpQz1QqAaOpIaOD2Cy08dudW8N+W/gtA4rxPaedqmvWbntttzQfzBjdYibiEt61ZYh/Q72vGrMC6oMTaXDhcCTjnBIQhbD5tgjHC08++M7bfj3iU5zxbQ5nSxBgN8hgJfNPR4LSTUPMTM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
